#! /bin/bash


# echo the environment settings for http api tests
#

source ./define.sh

echo STORE_URL=${STORE_URL}
echo STORE_HOST=${STORE_HOST}
echo STORE_ACCOUNT=${STORE_ACCOUNT}
echo STORE_REPOSITORY=${STORE_REPOSITORY}
echo STORE_TOKEN=${STORE_TOKEN}
echo STORE_TOKEN_JHACKER=${STORE_TOKEN_JHACKER}
echo STORE_PREFIX=${STORE_PREFIX}
echo STORE_DGRAPH=${STORE_DGRAPH}
echo STORE_IGRAPH=${STORE_IGRAPH}
echo STORE_NAMED_GRAPH=${STORE_NAMED_GRAPH}
echo STORE_NAMED_GRAPH_URL=${STORE_NAMED_GRAPH_URL}
echo STORE_IS_LOCAL=${STORE_IS_LOCAL}
