#! /bin/bash

${CURL} -s -k -X POST --user ":${LDP_TOKEN}" --data-binary @- \
  -H "Content-Type: text/turtle" \
  -H "Link: <http://www.w3.org/ns/ldp#RDFSource>; rel=type" \
  -H "Slug: foaf" \
  "https://${LDP_HOST}/${LDP_REPOSITORY}/ldp?resource=http://example.org/alice/" <<EOF > result.ttl
@prefix dc: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

<> a foaf:PersonalProfileDocument;
    foaf:primaryTopic <#me> ;
    dc:title 'Alice’s FOAF file' .

<#me> a foaf:Person;
    foaf:name 'Alice Smith'  .   
EOF
