# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Provide utilities
      - name install utilities
        sudo apt-get update
        sudo apt-get install -qq raptor2-utils
        sudo apt-get install -qq yajl-tools
        sudo apt-get install -qq jq
        sudo apt-get install -qq graphviz
        sudo apt-get install -qq tidy
        sudo apt-get install -qq libxml2-utils
        
      # Runs a single command using the runners shell
      - name: run all tests
        shell: bash
        env:
          STORE_HOST: ${{ secrets.STORE_HOST }}
          STORE_TOKEN: ${{ secrets.STORE_TOKEN }}
        run: bash run_all.sh
        
